### ISSUE TITLE
[Auth] Add kerberos auth

### ISSUE THREAD

**Issue by Dubrzr** [senx/warp10-platform#284]
Hi,

As Warp 10 uses Hadoop based software (Hbase, Kafka, Zookeeper), that would be awesome to make it work with Kerberized Hadoop. It would also mean some that you bring some concurrence to Druid (which does not currently support <millisecond metric precision)

Do you think you could add Kerberos support?

**Comment by hbs** [comment]
This is not currently on the roadmap, but let's see if this issue gathers some interest.

As far as druid is concerned, you can connect the analytics part of Warp 10 to Druid via a simple WarpScript extension which should be very easy to draft. Then the actual meaning of timestamps in druid won't matter at all since the analytics would not be done in Druid.

**Comment by hbs** [comment]
Closing this issue for now as no other request has been done to support Kerberos auth since 2018.

The issue could be re-opened if needed.
