### ISSUE TITLE
GTS estimator update at the start of the month

### ISSUE THREAD

**Issue by miton18** [senx/warp10-platform#563]
Hi !

When an app produces some datapoints, the `warp.gts.distinct.perapp` is well incremented.

However when the app stop to push datapoints on this series, and wait until the end of the month, the `warp.gts.distinct.perapp` is not reset.

Even after the 1st of the month, the `warp.gts.distinct.perapp` value stay the same.

I have to push 1 datapoint on each Ingress to locally resets the `warp.gts.distinct.perapp` value at the start of each new month.

Is it possible to force the reset of this metric each start of the month ? or at least to synchronize the Ingresses ?

**Comment by hbs** [comment]
The estimators are reset in an opportunistic manner, meaning that update is only done when new datapoints are pushed, this has the side effect you describe, i.e. that the last known value of an estimator cardinality is carried over the end of the month if no new datapoint was pushed for the given application or producer.

The estimators are merged periodically if the throttling topic was specified in the configuration, but that merge operation does not currently update the associated sensision metric.

What could be done is twofold, the merge operation could update the associated metric, and a cleanup thread could be added that will set to 0 the metric of all expired estimators (those which were not updated since the beginning of the month) with a short TTL so that metric does not survive past 24 hours for example.
