### ISSUE TITLE
Add ability to get WEBCALL result

### ISSUE THREAD

**Issue by bensmrs** [senx/warp10-platform#697]
There is AFAIK no way to get the result of a WEBCALL. What would be good is a function that takes as an input the UUID of the request and returns a 4-elements list, as URLFETCH does, or a special value if the request is still pending. It would allow one to get for example the result of a POST action or detect if a request needs to be resent.

**Comment by hbs** [comment]
WEBCALL is asynchronous and may be distributed so the simplest way we could store and give access to the result would be via a GTS.

In order to make this as generic as possible I suggest to add the ability to define a webcall macro in the configuration, this macro would get called after WEBCALL issues the actual call and will do whatever you want, send an email, send a text message, store something in a GTS, etc etc. It could be passed the same parameters as the WEBCALL call so a decision can be made based on the headers for example.

**Comment by bensmrs** [comment]
The idea of a hook macro is indeed interesting, but it assumes some kind of uniformity in the way WEBCALLs are used. If I'm using a macro that does some WEBCALLs and doesn't care about the result, but I have two scripts that each do specific WEBCALLs and need to process the output, upon completion of the request, in two different ways, that would result in big nested SWITCH clauses and hinder readability.
The idea of a GTS solves this, as one would only need to FETCH the proper GTS to get the result.
I think that a hook is more relevant though, but what would be great is the ability to specify a hook macro for each WEBCALL issued. This way, heterogeneous WEBCALLs could be handled by different macros, specific to one use case or another.

**Comment by hbs** [comment]
The idea is to be able to specify a macro in the configuration file, this macro could then use the value of a given header as the name of an actual macro to execute giving all the flexibility you wished.

**Comment by hbs** [comment]
Indirectly solved by PR #891
