### ISSUE TITLE
Count based fetch returns extraneous datapoints

### ISSUE THREAD

**Issue by pi-r-p** [senx/warp10-platform#877]
Kind duplicate of #81 , years later.
```
[ 
'token'
    'classname' 
  { "uuid" "50d6755b-3b7a-47a8-a4f0-687ff4c78897"  }
  NOW -1
] 
FETCH
```

returns 2 points

```
[ 
'token'
    'classname' 
  {  }
  NOW -1
] 
FETCH
<% 
  LABELS 'uuid' GET "50d6755b-3b7a-47a8-a4f0-687ff4c78897" ==
%> FILTERBY
```

returns two distinct GTS

**Comment by pi-r-p** [comment]
OK, There is two different series with different producers in the database.
should the FETCH merge anyway or not ?

**Comment by hbs** [comment]
The series have differing producer/owner, if they are fetched consecutively they will be identified as matching, but if they are fetched with other GTS fetched in between (if fetching more than 2 for example), then the fusion will not be possible. Since this is linked to the use of special tokens (which retrieve series from multiple producers/owners), this is tolerable. You can always add the '.expose' token attribute to expose the producer and owner.
