### ISSUE TITLE
[enhancement] Mutual ClassLoader for plugin and extension that are from the same jar.

### ISSUE THREAD

**Issue by randomboolean** [senx/warp10-platform#972]
By default, each plugin and extension have their own class loader, even if they come from the same jar. One example of limitation is that they can not share ressources like static variables.

A workaround is to declare the use of the default class loader (inherited from Warp 10) in the Warp 10 configuration files for both the plugin and the extension. Should it be intended this way or may we implement a way to load a set of modules (extensions and/or plugins) with a same class loader ?

**Comment by hbs** [comment]
Independent plugins and extensions should not share anything since they have no knowledge they were loaded in the same Warp 10 instance. For the cases when an extension is tightly linked to a plugin, the best practice used so far is to register the extension from the plugin and simply declare the plugin in the Warp 10 configuration, therefore both the plugin and extension will be loaded by the same class loader (that loading the plugin) and they will be able to tickle each other.

**Comment by randomboolean** [comment]
Thanks for this workaround. I didn't thought that an extension could be registered from anywhere.
